# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 968605f2d9de2ebc9a69558daa580c551d6b07877d2b1300692d807a6757f0b53cfe4f00f6201de70814bfc9b8474cba20883b8970896477afd75852ea0d855e

test:
  secret_key_base: 6ef27cc345c530e3594d60eadb0b3d582c850bc198f8113b6ae2cebbfe6022e4fd66dd1ffba7cdc764c11de70c8da6ce9771bea3d2b162a3de5d858921132901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
